config/routes.rb
Jobsatosu::Application.routes.draw do

  root 'welcome#index'                        # Route to index page
  post 'email_job'  =>  'welcome#email_job'   # Route to email job details
  post 'change_view'=>  'welcome#change_view' # Route to switch between views
  post 'contact_us' =>  'welcome#contact_us'  # Route to let user contact the HR via email
end

app/models/jobs.rb
class Jobs < ActiveRecord::Base
  require 'will_paginate/array'

  # Model self callable method to update the data from atom feed
  def self.update_from_feed(feed_url)
    Jobs.delete_all
    feed = Feedjira::Feed.fetch_and_parse(feed_url)
    feed.entries.each do |entry|
      unless exists? :id=>entry.id
        create!(
          :id         =>  entry.id,
          :link       =>  entry.url,
          :title      =>  entry.title,
          :author     =>  entry.author,
          :content    =>  entry.content,
          :updated_at =>  entry.updated,
          :created_at =>  entry.published,
        )
      end
    end
  end

  # Method to validate the existing data/jobs with the latest atom feed
  def self.validate_from_feed(new_feed)
    Jobs.delete_all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  require 'feedjira'
  helper_method :sort_column, :sort_direction, :send_email
  $view_field = 'list'
  $mesg=''

  def index
    # To fetch the atom feed for the first time
    initial_feed

    # Verifies for any search keyword and responds accordingly
    @entries = params[:search]&&params[:search]!='*'?searchable(params[:search]).paginate(:page => params[:page], :per_page => 50):
              Jobs.order(sort_column+' '+sort_direction).paginate(:page => params[:page], :per_page => 50)
  end

  # Method to support the view switching functionality
  def change_view
    $view_field = params[:view]
    redirect_to root_path
  end

  # Method to email the job details
  def email_job
    send_email(params[:email_id], params[:job_id])
    flash[:success]='Email has been successfully sent.'
    redirect_to root_path
  end

  # Method to provide email channel to Jobs Dept. to interested user
  def contact_us
    $mesg = params[:msg]
    send_email('anish.bharata@gmail.com','')
    flash[:success]='Your message has been successfully sent.'
    redirect_to root_path
  end

  private
  # Private method to perform search operation
  def searchable(keyword)
    Jobs.where('CAST(id AS TEXT) LIKE ? OR LOWER(title) LIKE LOWER(?) OR LOWER(author) LIKE LOWER(?)','%'+keyword+'%','%'+keyword+'%','%'+keyword+'%')
  end

  # Private method to perform initial fetch from Atom feed
  def initial_feed
    if(Jobs.count==0)
      Jobs.update_from_feed('https://www.jobsatosu.com/all_jobs.atom.xml')
    end
  end

  # Private method to sort the column values alphabetically
  def sort_column
    Jobs.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end

  # Private method to enable sorting in both ascending & descending directions
  def sort_direction
    #params[:direction]?params[:direction]:'asc'
    %w[asc desc].include?(params[:direction])?params[:direction] : 'asc'
  end

  # Private method to send email through SEND GRID
  def send_email(email_id, job_id)
    # As a hash
    @temp = Jobs.where(:id=>job_id).first
    client = SendGrid::Client.new(api_user: ''+ENV['SENDGRID_USERNAME'], api_key: ''+ENV['SENDGRID_KEY'])
    if !$mesg.blank?
      client.send(SendGrid::Mail.new(to: email_id, from: 'JobsatOSU', subject: 'JobsatOSU-Contact Us Page',
                                     text:'JobsatOSU-Contact Us Page', html: $mesg.to_s ))
    else
      client.send(SendGrid::Mail.new(to: email_id, from: 'Jobsatosu.com',
                                     subject: 'OSU Looking For '+@temp.title.to_s,
                                     text:'OSU Job Alert '+@temp.title.to_s,
                                     html: '<h3>Title: '+@temp.title.to_s+'</h3>'+
                                       '<h3>Posted by: '+@temp.author.to_s+'</h3> at '+@temp.created_at.to_s+
                                       '<p class=\'text-justify\'>Description: '+@temp.content.to_s+'</p>'+
                                       'Interested? <a href='+@temp.link.to_s+' target=\'_blank\'>Click here for more details.</a>'+
                                       '<p>--Thank you for your interest in OSU.</p><p>Sent to you by JobsAtOSU.</p>' ))
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Helper method to verify and assign the sorting-direction
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == 'asc'?'desc':'asc'
    link_to title, {:sort => column, :direction =>direction}, {:class => css_class}
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jobsatosu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico'%>
  <link href='https://fonts.googleapis.com/css?family=Exo+2:900italic,400' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Alegreya+Sans:1000,900' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Ubuntu:400,700' rel='stylesheet' type='text/css'>
  <script type='text/javascript'>var switchTo5x=true;</script>
  <script type='text/javascript' src='https://ws.sharethis.com/button/buttons.js'></script>
  <script type='text/javascript'>stLight.options({publisher: 'ff59828b-44f7-4e0e-b6db-6049185ea2c4', doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
  <%= csrf_meta_tags %>
</head>
<body>
<marquee><b class='alert-danger'><span class='glyphicon glyphicon-warning-sign'></span> THIS IS NOT A PRODUCTION SITE.
  <span class='glyphicon glyphicon-exclamation-sign'></span>STRICTLY BUILD FOR DEMO PURPOSES ONLY.</b></marquee>

    <div class='container'>
      <div class='row col-sm-8 heading'>
        <%=link_to '<h2>JOBSAT</h2><h2 class=\'osu\'>OSU</h2>'.html_safe, root_url%>
        <p class='caption'>100 Best Adoption Friendly Workplaces -2014</p>
      </div>
      <div class='col-sm-4' style='margin-top: 20px;'>
        <a href='https://plus.google.com/+ohiostateuniversity/about' target='_blank' title='Google Plus'>
          <%= image_tag 'googleplus-64.png', :class=>'social', :width=>'50'%>
        </a>
        <a href='https://www.facebook.com/osu' target='_blank' title='Facebook'>
          <%= image_tag 'facebook-64.png', :class=>'social', :width => '50'%>
        </a>
        <a href='https://twitter.com/ohiostate' target='_blank' title='Twitter'>
          <%= image_tag 'twitter-64.png', :class=>'social', :width => '50'%>
        </a>
        <a href='https://www.youtube.com/user/OhioStateUniversity' target='_blank' title='Youtube'>
          <%= image_tag 'youtube-64.png', :class=>'social', :width=>'50'%>
        </a>
        <a href='https://www.linkedin.com/edu/the-ohio-state-university-19133' target='_blank' title='LinkedIn'>
          <%= image_tag 'linkedin-64.png', :class=>'social', :width=>'50'%>
        </a>
        <a href='#' alt='Contact Us' title='Contact Us' data-toggle='modal' data-target='.bs-example-modal-sm'>
          <%= image_tag 'email-64.png', :class=>'social', :width=>'50', :alt=>'Contact Us'%>
        </a>
      </div>

      <%=render 'welcome/contactUs'%>

  <div class='row col-sm-12'>
    <% flash.each do |key, value| %>
      <div class='alert alert-<%= key %> alert-dismissible'><%= value %>
        <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
      </div>
    <% end %>
  </div>
  <div class='row'>
    <%render 'welcome/searchBlock'%>
  </div>

    <%= yield %>

  <div class='row col-sm-12 text-center'>
    <p>Developed by ABB.</p>
  </div>
    </div>
</body>
</html>

app/views/welcome/_contactUs.html.erb
<div class='modal fade bs-example-modal-sm' tabindex='-1' role='dialog' aria-labelledby='mySmallModalLabel' aria-hidden='true'>
  <div class='modal-dialog model-sm'>
    <div class='modal-content'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
        <h4 class='modal-title' id='exampleModalLabel'>Contact Us</h4>
      </div>

      <%=form_tag contact_us_path, :method=>'post' do |f|%>
      <div class='modal-body'>
          <div class='form-group'>
            <label for='recipient-name' class='control-label'>*Sender:</label>
            <%=email_field_tag :email_id, params[:email_id], :class=>'form-control input-xs',
                               :required=>'true', :placeholder=>'Email Address'%>
          </div>
          <div class='form-group'>
            <label for='message-text' class='control-label'>*Message:</label>
            <%=text_area :msg, params[:msg], :class=>'form-control', :required=>'true',
                                :placeholder=>'Type your message here...'%>
          </div>
      </div>
      <div class='modal-footer'>
        <button type='button' class='btn btn-sm btn-default' data-dismiss='modal'>Close</button>
        <%=submit_tag :'Send', :name=>nil, :class=>'btn btn-sm btn-success'%>
      </div>
      <%end%>

    </div>
  </div>
</div>

app/views/welcome/_gridView.html.erb
<div class='row'>
  <div class='col-sm-1'><%=link_to "<span class='glyphicon glyphicon-th-list' aria-hidden='true'></span>".html_safe,{:controller=>'welcome', :action=>'change_view',:view=>'list'},
               :class=>'btn btn-danger btn-sm',:method=>:post%></div>
  <div class='col-sm-3'>Total <%=@entries.length%> of <%=@entries.count%> Jobs</div>
  <div class='col-sm-4 pull-right'><%= will_paginate @entries%></div>
</div>

<%@entries.each do |job| %>
    <div class='row col-sm-12'>
      <div class='panel panel-default'>
        <div class='panel-heading'>
          <h3 class='panel-title'><b><%=job.title%></b> role with <b><%=job.author%></b></h3>
        </div>

        <div class='panel-body article'>
          <p class='text-justify'><%=job.content.html_safe%></p>
          <%=link_to "<button type='button' class='btn btn-xs btn-success'>Open in University Site</button>".html_safe,
                     job.link, :target=>'_blank'%>
          <small class='pull-right'>
            <p><span class='st_facebook'></span>
              <span class='st_twitter'></span>
              <span class='st_linkedin'></span>
              <span class='st_email'></span>
                Posted <%=job.created_at%>
              <%if job.updated_at.to_s!=job.created_at.to_s%> and Updated at<%=job.updated_at%><%end%>
            </p>
          </small>
        </div>
      </div>
    </div>

    <div class='col-sm-1'></div>
<%end%>
<script>
    $('.article').readmore({
        speed: '200',
        lessLink: '<a href="#">Read less</a>'
    });
</script>

app/views/welcome/_listView.html.erb
<div class='row'>
  <div class='col-sm-1'><%=link_to "<span class='glyphicon glyphicon-th' aria-hidden='true'></span>".html_safe,{:controller=>'welcome', :action=>'change_view',:view=>'grid'},
             :class=>'btn btn-danger btn-sm',:method=>:post%></div>
  <div class='col-sm-3'>Total <%=@entries.length%> of <%=@entries.count%> Jobs</div>
  <div class='col-sm-3 text-warning'>*Click on the columns for sorting</div>
  <div class='col-sm-4 pull-right'><%= will_paginate @entries%></div>
</div>

<table class='table no-bordered'>
  <thead>
  <tr>
    <th><%#= sortable 'id', 'Id'%></th>
    <th><%= sortable 'title', 'Title '%><span class='glyphicon glyphicon-sort'></span></th>
    <th><%= sortable 'author', 'Department '%><span class='glyphicon glyphicon-sort'></span></th>
    <th><%= sortable 'created_at', 'Posted On '%><span class='glyphicon glyphicon-sort'></span></th>
  </tr>
  </thead>
  <tbody>
  <%@entries.each do |job| %>
      <tr class='no-border'>
        <td><%#=job.id%></td>
        <td><a data-toggle='modal' data-target='#<%=job.id%>' href='#' class='job_title'><%=job.title%></a></td>
        <td class='job_author'><%=job.author%></td>
        <td><small><%=job.created_at%></small>
          <%if job.updated_at.to_s!=job.created_at.to_s%>
              Updated at<%=job.updated_at%>
          <%end%>
        </td>
        <td>
          <!-- START OF MODAL -->
          <div class='modal fade' id='<%=job.id%>' role='dialog' aria-labelledby='myModalLabel'>
            <div class='modal-dialog'>
              <div class='modal-content'>
                <div class='modal-header'>
                  <button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
                  <h4 class='modal-title lead' id='myModalLabel'><%=job.title%></h4>
                </div>

                <div class='modal-body'>
                  <strong class='pull-right'>Posted by <%=job.author%></strong>
                  <h5>Summary of Duties</h5>
                  <p class='text-justify'><%=job.content.html_safe%></p>

                  <%=link_to "<button type='button' class='btn btn-xs btn-success'>Open in University Site</button>".html_safe,
                             job.link, :target=>'_blank'%>

                </div>
                <div class='modal-footer form-inline'><!--<div class='modal-footer form-inline'>-->
                  <%= form_tag email_job_path, :method=>'post', :class=>'form-inline' do |f|%>
                      <label>  <span class='glyphicon glyphicon-envelope'></span> Email this job? </label>
                      <%=email_field_tag :email_id, params[:email_id], :class=>'form-control input-xs',
                                         :required=>'true', :placeholder=>'Email Address'%>
                      <%=hidden_field_tag :job_id, job.id %>
                      <div class='form-group'>
                        <%=submit_tag :'Email this job', :name=>nil, :class=>'btn btn-xs btn-success'%>
                      </div>
                  <%end%>
                </div>
              </div>
            </div>
          </div><!--END OF MODAL-->
        </td>
      </tr>

  <%end%>
  </tbody>

</table>
<%= will_paginate @entries%>

app/views/welcome/_searchBlock.html.erb
<%= form_tag root_path, :method=>'get', :class=>'form-inline', :style=>'margin-bottom:20px;' do |f|%>
    <%=text_field_tag :search, params[:search], :class=>'form-control input-lg',
                      :style=>'width:80%',:required=>'true', :placeholder=>'Type in Job Id or Role or Department'%>
    <div class='form-group btn-group-lg'>
      <%=submit_tag :'Search Jobs', :name=>nil, :class=>'btn btn-success'%>
    </div>
<%end%>

app/views/welcome/index.html.erb
<div class='row'>
  <div class='col-sm-3'>
      <%if @entries.size==0%><p>No Jobs to show.</p><%end%>
  </div>
  <div class='col-sm-9'></div>
</div>
<%=render 'searchBlock'%>

<%if $view_field=='list'%>
    <%=render 'listView'%>
<%else%>
    <%=render 'gridView'%>
<%end%>